### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by lcoutinhovv** [mongo-flink/mongo-flink#1]
Hi,
I have the need to implement flink using the MongoDB sink, and I really liked this project! But it was not clear how to implement it in flink, is it possible to attach, or send me some examples of use?

**Comment by link3280** [comment]
Sure. Apologies for the lack of documents, cause this project is in its early phase. Please see [MongoTransactionalSinkTest](https://github.com/mongo-flink/mongo-flink/blob/master/src/test/java/mongoflink/sink/MongoTransactionalSinkTest.java) for the example usage.

**Comment by lcoutinhovv** [comment]
@link3280 I even looked at this file, but I still couldn't understand how it would look in a stream that reads Kafka data for example, something like:
`  public static void main(String... args) throws Exception {
        String topic = System.getenv("TOPIC");
        String propertiesPath = System.getenv("PROPERTIES_PATH");


        final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        Properties propertiesCorp = new Properties();
        propertiesCorp.load(new FileReader(propertiesPath));

        DataStream<String> streamCorp = env.addSource(new FlinkKafkaConsumer(topic, new SimpleStringSchema(), propertiesCorp));

//MongoDB Insert implementation
        streamCorp.addSink(new MongoSink....);

        env.execute("Pipeline test");

    }`

**Comment by link3280** [comment]
@lcoutinhovv Would you mind bumping up the flink version of your application?  Or you may need to implement your own MongoDB sink using the old SinkFunction API. MongoBulkWriter probably has some snippets you can use.

**Comment by link3280** [comment]
Close this issue since the discussion is not active. Reopen it if needed.
