### ISSUE TITLE
Publish version 0.2 to Maven

### ISSUE THREAD

**Issue by madsjk816** [mongo-flink/mongo-flink#10]
Is it possible that you can publish v. 0.2 to Maven? At the current moment it looks like that only 0.1 is available :)

https://repo1.maven.org/maven2/org/mongoflink/mongo-flink/

**Comment by link3280** [comment]
@madsjk816 Thanks for pointing it out. I forgot to activate the release profile. Now it's available on the Maven repo.

**Comment by madsjk816** [comment]
@link3280 Very much appreciated, thank you! 👍
