### ISSUE TITLE
Any plans to publish to maven central? 

### ISSUE THREAD

**Issue by JoakimFristedt** [mongo-flink/mongo-flink#3]
Hi, 

I want to run this connector, are there any plans in the near future to publish to mvn central?

**Comment by link3280** [comment]
@JoakimFristedt Hi, now MongoFlink is published to maven central but is tightly coupled to the flink version. We may need to build multiple artifacts to cover the active Flink versions in the future. 

I hope this meets your need. It would be great if you can try it out and give us feedback.
