### ISSUE TITLE
if bulk.getDocuments().size() == 0

### ISSUE THREAD

**Issue by ck-gao** [mongo-flink/mongo-flink#4]
when insertMany(bulk.getDocuments()), make sure bulk.getDocuments().size>0? 
原因是我在程序启动后不向kafka写入数据，等过了MongoOptions.SINK_FLUSH_INTERVAL刷新时间后，再插入数据还有 state should be: writes is not an empty list 错误。

**Comment by link3280** [comment]
Thanks for reporting this bug. Would you like to contribute a fix? If not, I'm fixing if myself.
